@extends('layouts.autumnLayout', ['kzLink' => null, 'ruLink' => null, 'enLink' => null])

@section('content')
    @include('pages.home.autumnComponents.announce', compact('announcements'))
    @include('pages.home.autumnComponents.mobileAnnounce', compact('announcements'))
    @include('pages.home.autumnComponents.counters', compact('counters'))
    @include('pages.home.autumnComponents.newsComponent', compact('news', 'latestArticle'))
    @include('pages.home.autumnComponents.feedback', compact('feedbacks'))
    @include('pages.home.autumnComponents.ads', compact('adverts'))
    @include('pages.home.autumnComponents.services', compact('services'))
    @include('pages.home.autumnComponents.information')
    @include('pages.home.autumnComponents.gallery', compact('gallery'))
    @include('pages.home.autumnComponents.awards', compact('awards'))
    @include('pages.home.autumnComponents.partners', compact('partners'))
@endsection
