@extends('layouts.summerLayout', ['kzLink' => null, 'ruLink' => null, 'enLink' => null])

@section('content')
    @include('pages.home.summerComponents.announce', compact('announcements'))
    @include('pages.home.summerComponents.mobileAnnounce', compact('announcements'))
    @include('pages.home.summerComponents.counters', compact('counters'))
    @include('pages.home.summerComponents.newsComponent', compact('news', 'latestArticle'))
    @include('pages.home.summerComponents.feedback', compact('feedbacks'))
    @include('pages.home.summerComponents.ads', compact('adverts'))
    @include('pages.home.summerComponents.services', compact('services'))
    @include('pages.home.summerComponents.information')
    @include('pages.home.summerComponents.gallery', compact('gallery'))
    @include('pages.home.summerComponents.awards', compact('awards'))
    @include('pages.home.summerComponents.partners', compact('partners'))
@endsection
