@extends('layouts.winterLayout', ['kzLink' => null, 'ruLink' => null, 'enLink' => null])

@section('content')
    @include('pages.home.swinterComponents.announce', compact('announcements'))
    @include('pages.home.swinterComponents.mobileAnnounce', compact('announcements'))
    @include('pages.home.swinterComponents.counters', compact('counters'))
    @include('pages.home.swinterComponents.newsComponent', compact('news', 'latestArticle'))
    @include('pages.home.swinterComponents.feedback', compact('feedbacks'))
    @include('pages.home.swinterComponents.ads', compact('adverts'))
    @include('pages.home.swinterComponents.services', compact('services'))
    @include('pages.home.swinterComponents.information')
    @include('pages.home.swinterComponents.gallery', compact('gallery'))
    @include('pages.home.swinterComponents.awards', compact('awards'))
    @include('pages.home.swinterComponents.partners', compact('partners'))
@endsection
