@extends('layouts.winterLayout', ['kzLink' => null, 'ruLink' => null, 'enLink' => null])

@section('content')
        @include('pages.home.winterComponents.announce', compact('announcements'))
        @include('pages.home.winterComponents.mobileAnnounce', compact('announcements'))
        @include('pages.home.winterComponents.counters', compact('counters'))
        @include('pages.home.winterComponents.newsComponent', compact('news', 'latestArticle'))
        @include('pages.home.winterComponents.feedback', compact('feedbacks'))
        @include('pages.home.winterComponents.ads', compact('adverts'))
        @include('pages.home.winterComponents.services', compact('services'))
        @include('pages.home.winterComponents.information')
        @include('pages.home.winterComponents.gallery', compact('gallery'))
        @include('pages.home.winterComponents.awards', compact('awards'))
        @include('pages.home.winterComponents.partners', compact('partners'))
@endsection
